# Generated by Django 5.2.10 on 2026-01-27 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='unknown.jpg', max_length=255)),
                ('prediction', models.CharField(default='UNKNOWN', max_length=10)),
                ('is_deepfake', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('real_probability', models.FloatField(default=0.0)),
                ('fake_probability', models.FloatField(default=0.0)),
                ('process_time', models.FloatField(default=0.0)),
                ('heatmap_path', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('facial_analysis_path', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_used', models.CharField(default='EfficientNet-B0', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Detection Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
