# Generated by Django 5.2.10 on 2026-02-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='artifact_map_path',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='deepfake_frames',
            field=models.IntegerField(default=0, help_text='Number of deepfake frames detected'),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='temporal_variance',
            field=models.FloatField(default=0.0, help_text='Temporal consistency variance'),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='total_frames',
            field=models.IntegerField(default=0, help_text='Total frames analyzed (0 for images)'),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='model_used',
            field=models.CharField(default='EfficientNet-B1', max_length=50),
        ),
        migrations.AddIndex(
            model_name='detectionhistory',
            index=models.Index(fields=['-created_at'], name='detector_de_created_80ba37_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionhistory',
            index=models.Index(fields=['file_type'], name='detector_de_file_ty_1e3a13_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionhistory',
            index=models.Index(fields=['is_deepfake'], name='detector_de_is_deep_1a27d4_idx'),
        ),
    ]
