# Generated by Django 5.2.10 on 2026-02-13 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_detectionhistory_artifact_map_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Detection History', 'verbose_name_plural': 'Detection Histories'},
        ),
        migrations.RemoveIndex(
            model_name='detectionhistory',
            name='detector_de_file_ty_1e3a13_idx',
        ),
        migrations.RemoveIndex(
            model_name='detectionhistory',
            name='detector_de_is_deep_1a27d4_idx',
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='artifact_map_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='deepfake_frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='facial_analysis_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='fake_probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='file_type',
            field=models.CharField(default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='heatmap_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='prediction',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='real_probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='temporal_variance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='total_frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='detectionhistory',
            index=models.Index(fields=['user', '-created_at'], name='detector_de_user_id_6457bb_idx'),
        ),
    ]
