# Generated by Django 5.2.10 on 2026-03-04 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_alter_detectionhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detectionhistory',
            index=models.Index(fields=['file_type', '-created_at'], name='detector_de_file_ty_be6dfa_idx'),
        ),
    ]
